databases:
  - name: ebanisiteria-leon
    databaseName: ebanisterialeon
    user: ebanisteria

services:
  - type: web
    name: ebanisteria
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ebanisteria.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ebaniteria-leon
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4